import { Category, Product } from "./types";

export const mockCategories: Category[] = [
    {
        id: "cat-1",
        name: "Rings",
        slug: "rings",
        image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=400&fit=crop",
        description: "Elegant rings for every occasion — engagement, wedding & everyday wear",
        created_at: new Date().toISOString(),
    },
    {
        id: "cat-2",
        name: "Earrings",
        slug: "earrings",
        image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
        description: "Studs, hoops, drops & jhumkas crafted to perfection",
        created_at: new Date().toISOString(),
    },
    {
        id: "cat-3",
        name: "Necklaces",
        slug: "necklaces",
        image_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=400&fit=crop",
        description: "Stunning necklaces & pendants from delicate chains to statement pieces",
        created_at: new Date().toISOString(),
    },
    {
        id: "cat-4",
        name: "Bracelets",
        slug: "bracelets",
        image_url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=400&fit=crop",
        description: "Bangles, cuffs & charm bracelets in gold, silver & rose gold",
        created_at: new Date().toISOString(),
    },
    {
        id: "cat-5",
        name: "Mangalsutra",
        slug: "mangalsutra",
        image_url: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&h=400&fit=crop",
        description: "Traditional & contemporary mangalsutra designs",
        created_at: new Date().toISOString(),
    },
    {
        id: "cat-6",
        name: "Anklets & Chains",
        slug: "anklets-chains",
        image_url: "https://images.unsplash.com/photo-1515562141589-67f0d569b6c4?w=600&h=400&fit=crop",
        description: "Delicate anklets and chains for a graceful finish",
        created_at: new Date().toISOString(),
    },
];

export const mockProducts: Product[] = [
    // Rings
    {
        id: "prod-1",
        name: "Rose Gold Solitaire Diamond Ring",
        slug: "rose-gold-solitaire-diamond-ring",
        description: "A breathtaking solitaire diamond ring set in 18K rose gold. Features a brilliant-cut 0.5 carat diamond with VS1 clarity. The delicate band is adorned with pavé-set diamonds for extra sparkle. Ideal for engagements, anniversaries, or as a timeless gift of love. Comes with a certificate of authenticity and premium gift box.",
        short_description: "18K rose gold, 0.5ct solitaire, pavé band",
        category_id: "cat-1",
        price: 32999,
        mrp: 45999,
        images: [
            "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop",
            "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800&h=800&fit=crop",
        ],
        tags: ["diamond", "rose gold", "solitaire", "engagement"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: null,
        is_featured: true,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-2",
        name: "Sterling Silver Infinity Band",
        slug: "sterling-silver-infinity-band",
        description: "An elegant infinity band crafted in 925 sterling silver with rhodium plating for a lasting shine. Embedded with AAA cubic zirconia stones in a channel setting. Hypoallergenic and suitable for daily wear. Perfect as a promise ring or stacking ring.",
        short_description: "925 silver infinity band with CZ stones",
        category_id: "cat-1",
        price: 1299,
        mrp: 2499,
        images: [
            "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800&h=800&fit=crop",
        ],
        tags: ["silver", "infinity", "band", "daily wear"],
        amazon_url: "https://amazon.in",
        flipkart_url: null,
        meesho_url: "https://meesho.com",
        is_featured: false,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-3",
        name: "Gold Floral Cocktail Ring",
        slug: "gold-floral-cocktail-ring",
        description: "A statement cocktail ring featuring intricate floral motifs in 22K gold. Set with natural rubies and diamonds. Adjustable shank for comfortable fit. This showstopper piece is perfect for weddings, parties, and festive occasions.",
        short_description: "22K gold floral ring with rubies & diamonds",
        category_id: "cat-1",
        price: 48999,
        mrp: 62000,
        images: [
            "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop",
        ],
        tags: ["gold", "cocktail", "ruby", "festive"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: "https://meesho.com",
        is_featured: true,
        is_trending: false,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    // Earrings
    {
        id: "prod-4",
        name: "Diamond Cluster Stud Earrings",
        slug: "diamond-cluster-stud-earrings",
        description: "Sparkling cluster stud earrings featuring 14 round-cut diamonds set in 14K white gold. Total diamond weight 0.75 carat. Secure push-back closure. These versatile studs transition beautifully from office wear to evening glamour.",
        short_description: "14K white gold, 0.75ct diamond cluster studs",
        category_id: "cat-2",
        price: 24999,
        mrp: 35999,
        images: [
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=800&fit=crop",
        ],
        tags: ["diamond", "studs", "white gold", "cluster"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: null,
        is_featured: true,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-5",
        name: "Traditional Gold Jhumka Earrings",
        slug: "traditional-gold-jhumka-earrings",
        description: "Handcrafted temple-style jhumka earrings in 22K gold with delicate filigree work and pearl drops. These traditional beauties feature antique tones and intricate craftsmanship passed down through generations. Perfect for weddings, puja, and festive celebrations.",
        short_description: "22K gold temple jhumkas with pearl drops",
        category_id: "cat-2",
        price: 38999,
        mrp: 52000,
        images: [
            "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&h=800&fit=crop",
        ],
        tags: ["gold", "jhumka", "traditional", "wedding"],
        amazon_url: "https://amazon.in",
        flipkart_url: null,
        meesho_url: "https://meesho.com",
        is_featured: false,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-6",
        name: "Rose Gold Hoop Earrings",
        slug: "rose-gold-hoop-earrings",
        description: "Classic hoop earrings in 18K rose gold with a brushed matte finish. 30mm diameter, lightweight, and comfortable for all-day wear. Hinged closure for easy on/off. A modern essential for every jewellery collection.",
        short_description: "18K rose gold matte hoops, 30mm",
        category_id: "cat-2",
        price: 8999,
        mrp: 13999,
        images: [
            "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&h=800&fit=crop",
        ],
        tags: ["rose gold", "hoops", "minimal", "daily wear"],
        amazon_url: null,
        flipkart_url: "https://flipkart.com",
        meesho_url: "https://meesho.com",
        is_featured: true,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    // Necklaces
    {
        id: "prod-7",
        name: "Layered Gold Chain Necklace",
        slug: "layered-gold-chain-necklace",
        description: "A chic multi-layered necklace featuring three delicate chains in 18K gold — a 16-inch choker, 20-inch pendant chain with a tiny heart charm, and a 24-inch cable chain. Each layer catches the light beautifully. Adjustable clasp for versatile styling.",
        short_description: "18K gold 3-layer chain with heart charm",
        category_id: "cat-3",
        price: 15999,
        mrp: 22999,
        images: [
            "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop",
        ],
        tags: ["gold", "layered", "chain", "pendant"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: null,
        is_featured: false,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-8",
        name: "Emerald & Diamond Pendant Set",
        slug: "emerald-diamond-pendant-set",
        description: "Luxurious pendant set featuring a pear-shaped Colombian emerald (1.2ct) surrounded by a diamond halo in 18K yellow gold. Comes with matching emerald stud earrings and a fine 18-inch box chain. A timeless piece for special occasions. Includes IGI certification.",
        short_description: "1.2ct emerald pendant set with diamond halo",
        category_id: "cat-3",
        price: 89999,
        mrp: 125000,
        images: [
            "https://images.unsplash.com/photo-1515562141589-67f0d569b6c4?w=800&h=800&fit=crop",
        ],
        tags: ["emerald", "diamond", "pendant", "luxury"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: "https://meesho.com",
        is_featured: true,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    // Bracelets
    {
        id: "prod-9",
        name: "Diamond Tennis Bracelet",
        slug: "diamond-tennis-bracelet",
        description: "Classic diamond tennis bracelet with 3.0 carats of round brilliant diamonds set in 14K white gold. Four-prong setting for maximum brilliance. Secure double-lock clasp. 7 inches with 0.5 inch extension. A timeless investment piece.",
        short_description: "3ct diamond tennis bracelet, 14K white gold",
        category_id: "cat-4",
        price: 149999,
        mrp: 199999,
        images: [
            "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop",
        ],
        tags: ["diamond", "tennis bracelet", "white gold", "luxury"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: null,
        is_featured: true,
        is_trending: false,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-10",
        name: "Gold Charm Bracelet",
        slug: "gold-charm-bracelet",
        description: "Playful charm bracelet in 18K yellow gold featuring 5 iconic charms — heart, star, moon, evil eye, and hamsa hand. Rolo chain design, 7 inches with lobster clasp. Each charm is detachable so you can customize your look.",
        short_description: "18K gold bracelet with 5 detachable charms",
        category_id: "cat-4",
        price: 18999,
        mrp: 27999,
        images: [
            "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop",
        ],
        tags: ["gold", "charm", "bracelet", "trendy"],
        amazon_url: "https://amazon.in",
        flipkart_url: null,
        meesho_url: "https://meesho.com",
        is_featured: false,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    // Mangalsutra
    {
        id: "prod-11",
        name: "Modern Diamond Mangalsutra",
        slug: "modern-diamond-mangalsutra",
        description: "A contemporary take on the traditional mangalsutra. 18K gold pendant with a floral diamond cluster mounted on genuine black beads. 18-inch length with extender chain. Perfect for the modern bride who values tradition with a twist.",
        short_description: "18K gold diamond floral pendant mangalsutra",
        category_id: "cat-5",
        price: 22999,
        mrp: 32999,
        images: [
            "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&h=800&fit=crop",
        ],
        tags: ["mangalsutra", "diamond", "modern", "bridal"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: null,
        is_featured: true,
        is_trending: false,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-12",
        name: "Classic Black Beads Mangalsutra",
        slug: "classic-black-beads-mangalsutra",
        description: "Traditional mangalsutra with double-string black beads and a hallmarked 22K gold pendant in a classic vati design. 22-inch length. Handcrafted by expert karigars. A beautiful symbol of marital bliss.",
        short_description: "22K gold vati pendant, double black beads",
        category_id: "cat-5",
        price: 15999,
        mrp: 21999,
        images: [
            "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&h=800&fit=crop",
        ],
        tags: ["mangalsutra", "gold", "traditional", "bridal"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: "https://meesho.com",
        is_featured: false,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    // Anklets & Chains
    {
        id: "prod-13",
        name: "Silver Ghungroo Anklet Pair",
        slug: "silver-ghungroo-anklet-pair",
        description: "A delightful pair of anklets in 925 sterling silver with tiny ghungroo bells and floral links. Adjustable length from 9 to 11 inches. The musical jingle of the bells adds a traditional charm to every step. Perfect for festive wear.",
        short_description: "925 silver anklets with ghungroo bells",
        category_id: "cat-6",
        price: 1899,
        mrp: 3499,
        images: [
            "https://images.unsplash.com/photo-1515562141589-67f0d569b6c4?w=800&h=800&fit=crop",
        ],
        tags: ["silver", "anklet", "ghungroo", "traditional"],
        amazon_url: "https://amazon.in",
        flipkart_url: "https://flipkart.com",
        meesho_url: "https://meesho.com",
        is_featured: false,
        is_trending: true,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-14",
        name: "18K Gold Italian Box Chain",
        slug: "18k-gold-italian-box-chain",
        description: "Premium Italian-made box chain in solid 18K yellow gold. 20 inches long, 1.2mm width. Smooth, anti-tangle design with a spring ring clasp. Perfect as a standalone piece or for hanging your favourite pendant. Hallmarked and hypoallergenic.",
        short_description: "18K gold Italian box chain, 20 inches",
        category_id: "cat-6",
        price: 12999,
        mrp: 18999,
        images: [
            "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop",
        ],
        tags: ["gold", "chain", "Italian", "minimal"],
        amazon_url: "https://amazon.in",
        flipkart_url: null,
        meesho_url: "https://meesho.com",
        is_featured: true,
        is_trending: false,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];
